#spring:
#  datasource:
#      druid:
#        driverClassName: com.mysql.cj.jdbc.Driver
##        url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
#        url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
#        username: test@localhost
#        password: test
#      initialSize: 5
#      minIdle: 1
#      maxActive: 50
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL spring.datasource.testWhileIdle=true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: false
#      filters: stat,wall,log4j
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 8081

# Logger Config
logging:
  level:
    root: warn
    com.lxy.mp.mapper: trace
  pattern:
    console: '%p%m%n'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: test@localhost
    password: test
